### PR TITLE
fix: default TEST_RUNNER_PATH windows

### PR DESCRIPTION
**Pull request by edenizk**
### Summary

PR for issue #255 

### Test plan

You can test it by running `yarn reassure` in windows in an example project

### CODE REVIEW

**Comment by edenizk** [comment]
> @edenizk I do not have Windows experience with Node. It looks like Windows versions does not have `.bin` folder for binaries. I've tried to find some docs around it but haven't found anything. Can you share any link regarding this topic?

@mdjastrzebski, I see that I have this folder in windows, but I think the problem might be because you cannot run shell scripts in Windows (tho someone reported recently in the #255 that they had the same problem in Mac). I have also tried to replace it with `jest.cmd` file, but it was giving a similar problem
image

When I was searching for this problem I found this page from jest, mb it can help :) 
https://jestjs.io/docs/troubleshooting#tests-are-failing-and-you-dont-know-why

also, another similar problem I've found is this one
https://github.com/facebook/jest/issues/4751#issuecomment-361063215

**Comment by mdjastrzebski** [comment]
@edenizk From the above links it seems like using `TEST_RUNNER_PATH='node_modules/.bin/jest.cmd'` (same folder, just added `.cmd` suffix) should be the recommended approach. But from what you are writing this does not work, right?

**Comment by edenizk** [comment]
> @edenizk From the above links it seems like using `TEST_RUNNER_PATH='node_modules/.bin/jest.cmd'` (same folder, just added `.cmd` suffix) should be the recommended approach. But from what you are writing this does not work, right?

yes exactly 🙂

it was also my first approach in another project (another computer win10), but it did not work.

I am getting another syntax error with this path in windows in both computers (win10 and win11)
image

**Review by mdjastrzebski — APPROVED** [review]
Looks good! @edenizk thank you for submitting the PR and your answers! 💯

**Pull request merged**
