### PR TITLE
chore: update example/native deps

### PR DESCRIPTION
**Pull request by mdjastrzebski**
### Summary

Update `examples/native` deps for React Native, Jest, RNTL

### Test plan

All checks and test pass.

### CODE REVIEW

**Comment by thymikee** [comment]
Merge when green 👍🏼

**Comment by mdjastrzebski** [comment]
Having multiple versions of React and React Native packages in monorepo can lead to various strange errors.

**Review by thymikee — APPROVED** [review]
👍🏼

**Comment by mdjastrzebski** [comment]
@thymikee looks like transition to React 18 could have made render count a bit random:
image

Is this concurrent mode in action?

**Comment by thymikee** [comment]
Huh, I missed that. Thought Strict Mode would kick in when tested components are explicitly wrapped in `React.StrictMode` in React 18, but it isn't the case here. 
cc @gaearon would you be able to assist maybe?

**Pull request merged**
