### PR TITLE
chore: upgrade expo example deps

### PR DESCRIPTION
**Pull request by mdjastrzebski**
### Summary

Update expo example to use Expo 46, React 18, React Native 0.69, RNTL 11.

### Test plan

All checks and tests pass.

### CODE REVIEW

**Comment by mdjastrzebski** [comment]
@thymikee I've noticed the same React 18 phenomenon related to render counts, as in native example:

image

Render durations curiously does not seem affected.

**Comment by thymikee** [comment]
Looking at the outlier AsyncComponent example, we don't clear the timeout there. It might be the source of the problem. Mind verifying?

**Comment by mdjastrzebski** [comment]
Which timeout do you mean? Jest test timeout?

**Comment by thymikee** [comment]
`setTimeout` in event handler

**Pull request merged**
