### PR TITLE
Setup Yarn 3

### PR DESCRIPTION
**Pull request by thymikee**
### Summary

Let's see how it goes

### CODE REVIEW

**Comment by thymikee** [comment]
@satya164 maybe we should commit the cache to the repo. Any experiences, pros/cons?

**Comment by satya164** [comment]
@thymikee cons: cloning the repo took significantly more time and made diffs harder to read when there were dep changes, pro: super quick to switch branches with different deps, simple CI setup since no caching-related config needed.

**Comment by mdjastrzebski** [comment]
Build fails with `example-native:build: Unknown Syntax Error: Unsupported option name ("--force").` Seems like our `yarn install --force` invocation.

**Comment by thymikee** [comment]
@satya164 thanks. For now I think we'll keep the global cache behavior. when switching branches locally on a hot cache it's pretty fast already

**Comment by mdjastrzebski** [comment]
Closing as stale.

**Pull request closed without merging**
